openapi: 3.0.3
info:
  title: Customer Inquiry API
  description: Public API endpoints for customer inquiry submission and verification
  version: 1.0.0
  contact:
    name: Cherish Support
    email: support@cherish.com

servers:
  - url: https://cherish-jiran.vercel.app
    description: Production
  - url: http://localhost:3000
    description: Local development

paths:
  /api/inquiries:
    post:
      summary: Submit a customer inquiry
      description: |
        Creates a new customer inquiry and sends a verification code via email.
        No authentication required. Called by external websites.
      operationId: createInquiry
      tags:
        - Inquiries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - email
                - name
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Brief subject of the inquiry
                  example: "Question about product features"
                content:
                  type: string
                  minLength: 1
                  maxLength: 5000
                  description: Detailed inquiry message
                  example: "I would like to know if your product supports..."
                email:
                  type: string
                  format: email
                  description: Customer email address for verification and responses
                  example: "customer@example.com"
                name:
                  type: string
                  minLength: 1
                  description: Customer full name
                  example: "John Doe"
                phone:
                  type: string
                  nullable: true
                  description: Optional phone number
                  example: "+1-555-123-4567"
      responses:
        '201':
          description: Inquiry created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Unique inquiry identifier
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  message:
                    type: string
                    example: "Inquiry submitted successfully. Check your email for verification code."
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Validation failed"
                details:
                  - field: "email"
                    message: "Invalid email format"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Failed to send verification email"

  /api/inquiries/verify:
    post:
      summary: Verify and retrieve inquiry details
      description: |
        Verifies customer identity using email and auth code, then returns inquiry details
        including any admin responses. No authentication required.
      operationId: verifyInquiry
      tags:
        - Inquiries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - authCode
              properties:
                email:
                  type: string
                  format: email
                  description: Email used when submitting inquiry
                  example: "customer@example.com"
                authCode:
                  type: string
                  pattern: '^[A-Z0-9]{6}$'
                  description: 6-character verification code from email
                  example: "ABC123"
      responses:
        '200':
          description: Inquiry found and verified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryDetail'
        '401':
          description: Invalid email or auth code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid email or verification code"
        '404':
          description: Inquiry not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "No inquiry found with provided credentials"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    InquiryDetail:
      type: object
      required:
        - id
        - title
        - content
        - email
        - name
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        title:
          type: string
          example: "Question about product features"
        content:
          type: string
          example: "I would like to know if your product supports..."
        email:
          type: string
          format: email
          example: "customer@example.com"
        name:
          type: string
          example: "John Doe"
        phone:
          type: string
          nullable: true
          example: "+1-555-123-4567"
        status:
          type: string
          enum:
            - pending
            - processing
            - completed
          example: "processing"
        createdAt:
          type: string
          format: date-time
          example: "2025-10-02T10:30:00Z"
        replyTitle:
          type: string
          nullable: true
          description: Admin response title (null if not yet replied)
          example: "Re: Question about product features"
        replyContent:
          type: string
          nullable: true
          description: Admin response content (null if not yet replied)
          example: "Thank you for your inquiry. Yes, our product supports..."
        repliedAt:
          type: string
          format: date-time
          nullable: true
          description: Timestamp of admin reply (null if not yet replied)
          example: "2025-10-02T14:15:00Z"

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
          description: Validation error details (if applicable)
